name: Get Alpine
on:
  push:
  workflow_dispatch:

jobs:
  alpine:
    strategy:
      max-parallel: 1
      matrix:
        include:
          - MMR: 3.18.0
            MM: 3.18
          - MMR: 3.18.1
            MM: 3.18
          - MMR: 3.18.2
            MM: 3.18
          - MMR: 3.18.3
            MM: 3.18
          - MMR: 3.18.4
            MM: 3.18
          - MMR: 3.18.5
            MM: 3.18
          - MMR: 3.18.6
            MM: 3.18
          - MMR: 3.19.0
            MM: 3.19
          - MMR: 3.19.1
            MM: 3.19
    runs-on: ubuntu-latest
    container: alpine:latest
    permissions: write-all

    steps:
      - name: Pre-Reqs
        run: |
          apk update
          apk add docker docker-cli docker-cli-buildx curl

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Import
        run: |
          docker import --platform aarch64 --message "Import tarball from alpine" --change "ENTRYPOINT /bin/ash" --change "ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" https://dl-cdn.alpinelinux.org/alpine/v${{ matrix.MM }}/releases/aarch64/alpine-minirootfs-${{ matrix.MMR }}-aarch64.tar.gz ghcr.io/${{ github.repository }}:${{ matrix.MMR }}-aarch64
          docker import --platform armhf   --message "Import tarball from alpine" --change "ENTRYPOINT /bin/ash" --change "ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" https://dl-cdn.alpinelinux.org/alpine/v${{ matrix.MM }}/releases/armhf/alpine-minirootfs-${{ matrix.MMR }}-armhf.tar.gz     ghcr.io/${{ github.repository }}:${{ matrix.MMR }}-armhf
          docker import --platform armel   --message "Import tarball from alpine" --change "ENTRYPOINT /bin/ash" --change "ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" https://dl-cdn.alpinelinux.org/alpine/v${{ matrix.MM }}/releases/armv7/alpine-minirootfs-${{ matrix.MMR }}-armv7.tar.gz     ghcr.io/${{ github.repository }}:${{ matrix.MMR }}-armel
          docker import --platform ppc64le --message "Import tarball from alpine" --change "ENTRYPOINT /bin/ash" --change "ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" https://dl-cdn.alpinelinux.org/alpine/v${{ matrix.MM }}/releases/ppc64le/alpine-minirootfs-${{ matrix.MMR }}-ppc64le.tar.gz ghcr.io/${{ github.repository }}:${{ matrix.MMR }}-ppc64le
          docker import --platform s390x   --message "Import tarball from alpine" --change "ENTRYPOINT /bin/ash" --change "ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" https://dl-cdn.alpinelinux.org/alpine/v${{ matrix.MM }}/releases/s390x/alpine-minirootfs-${{ matrix.MMR }}-s390x.tar.gz     ghcr.io/${{ github.repository }}:${{ matrix.MMR }}-s390x
          docker import --platform i386    --message "Import tarball from alpine" --change "ENTRYPOINT /bin/ash" --change "ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" https://dl-cdn.alpinelinux.org/alpine/v${{ matrix.MM }}/releases/x86/alpine-minirootfs-${{ matrix.MMR }}-x86.tar.gz         ghcr.io/${{ github.repository }}:${{ matrix.MMR }}-i386
          docker import --platform x86_64  --message "Import tarball from alpine" --change "ENTRYPOINT /bin/ash" --change "ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" https://dl-cdn.alpinelinux.org/alpine/v${{ matrix.MM }}/releases/x86_64/alpine-minirootfs-${{ matrix.MMR }}-x86_64.tar.gz   ghcr.io/${{ github.repository }}:${{ matrix.MMR }}-x86_64

      - name: Push
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ matrix.MMR }}-aarch64
          docker push ghcr.io/${{ github.repository }}:${{ matrix.MMR }}-armhf
          docker push ghcr.io/${{ github.repository }}:${{ matrix.MMR }}-armel
          docker push ghcr.io/${{ github.repository }}:${{ matrix.MMR }}-ppc64le
          docker push ghcr.io/${{ github.repository }}:${{ matrix.MMR }}-s390x
          docker push ghcr.io/${{ github.repository }}:${{ matrix.MMR }}-i386
          docker push ghcr.io/${{ github.repository }}:${{ matrix.MMR }}-x86_64
      
      - name: Cleanup
        run: |
          docker image rm ghcr.io/${{ github.repository }}:${{ matrix.MMR }}-aarch64
          docker image rm ghcr.io/${{ github.repository }}:${{ matrix.MMR }}-armhf
          docker image rm ghcr.io/${{ github.repository }}:${{ matrix.MMR }}-armel
          docker image rm ghcr.io/${{ github.repository }}:${{ matrix.MMR }}-ppc64le
          docker image rm ghcr.io/${{ github.repository }}:${{ matrix.MMR }}-s390x
          docker image rm ghcr.io/${{ github.repository }}:${{ matrix.MMR }}-i386
          docker image rm ghcr.io/${{ github.repository }}:${{ matrix.MMR }}-x86_64

      - name: Merge
        run: |
          docker buildx imagetools create \
            ghcr.io/${{ github.repository }}:${{ matrix.MMR }}-aarch64 \
            ghcr.io/${{ github.repository }}:${{ matrix.MMR }}-armhf \
            ghcr.io/${{ github.repository }}:${{ matrix.MMR }}-armel \
            ghcr.io/${{ github.repository }}:${{ matrix.MMR }}-ppc64le \
            ghcr.io/${{ github.repository }}:${{ matrix.MMR }}-s390x \
            ghcr.io/${{ github.repository }}:${{ matrix.MMR }}-i386 \
            ghcr.io/${{ github.repository }}:${{ matrix.MMR }}-x86_64 \
            -t ghcr.io/${{ github.repository }}:${{ matrix.MMR }}
